---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv-volume-mysql-0
  namespace: mysql-cluster
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/db/mysql-0 
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv-backup-mysql-0
  namespace: mysql-cluster
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/backup/mysql-0
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv-volume-mysql-1
  namespace: mysql-cluster
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/db/mysql-1 
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv-backup-mysql-1
  namespace: mysql-cluster
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/backup/mysql-1
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv-volume-mysql-2
  namespace: mysql-cluster
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/db/mysql-2
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv-backup-mysql-2
  namespace: mysql-cluster
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/backup/mysql-2
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual

