---
apiVersion: v1
kind: Service
metadata:
  name: mysql-0
  namespace: mysql-cluster
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-0
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-1
  namespace: mysql-cluster
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-1
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-2
  namespace: mysql-cluster
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-2
  clusterIP: None

